### ISSUE TITLE
Syntax error in node_modules/junk/index.js

### ISSUE THREAD

**Issue by XTermV0** [mrvautin/adminMongo#106]
Hi,

I always receive syntax error on adminmongo, when i am trying to add new database connection:

```
root@cs44686:/opt/adminMongo# npm start

> admin-mongo@0.0.20 start /opt/adminMongo
> node app.js

adminMongo listening on host: http://0.0.0.0:1234

/opt/adminMongo/node_modules/junk/index.js:24
exports.is = filename => exports.re.test(filename);
                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.exports.get_backups (/opt/adminMongo/routes/common.js:41:16)
    at /opt/adminMongo/routes/index.js:143:16
    at /opt/adminMongo/routes/common.js:35:9
    at /opt/adminMongo/node_modules/mongodb/lib/admin.js:163:7
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

AdminMongo v 0.0.20 installed from git. Ubuntu 14.04.5 x64

**Comment by mrvautin** [comment]
What version of NodeJs are you running? I'm thinking it is old.

**Comment by XTermV0** [comment]
I use standard nodejs package from ubuntu repo: 

```
# dpkg -s nodejs
...
Version: 0.10.25~dfsg2-2ubuntu1
```


I am trying to start adminmongo on newest Ubuntu 16.04 with nodejs 4.2.6 and all is OK.

I will update my nodejs version.

Thanks for reply!
