### ISSUE TITLE
Crash on New Document/Insert

### ISSUE THREAD

**Issue by sagargulati** [mrvautin/adminMongo#108]
Hello,
I am running adminMongo on my domain.com/adminMongo
it works normally fine but when i add or insert a new document it crashes, i have checked in NPM for errors:

Here it what it shows on crash

```

TypeError: Cannot read property '0' of undefined
    at /root/developer/screens/adminMongo/routes/index.js:607:104
    at handleCallback (/root/developer/screens/adminMongo/node_modules/mongodb/lib/utils.js:96:12)
    at Object.cb (/root/developer/screens/adminMongo/node_modules/mongodb/lib/collection.js:1041:5)
    at /root/developer/screens/adminMongo/node_modules/mongodb-core/lib/connection/pool.js:446:18
    at authenticateStragglers (/root/developer/screens/adminMongo/node_modules/mongodb-core/lib/connection/pool.js:402:16)
    at null.messageHandler (/root/developer/screens/adminMongo/node_modules/mongodb-core/lib/connection/pool.js:424:5)
    at Socket.<anonymous> (/root/developer/screens/adminMongo/node_modules/mongodb-core/lib/connection/connection.js:294:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! admin-mongo@0.0.12 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-mongo@0.0.12 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the admin-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs admin-mongo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls admin-mongo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/developer/screens/adminMongo/npm-debug.log
root@wolf:~/developer/screens/adminMongo# npm start

> admin-mongo@0.0.12 start /root/developer/screens/adminMongo
>
```

npm starts work fine, i am running it behind a "screen" using "npm start"

Please help!

Thanks!

**Comment by mrvautin** [comment]
The error shouldn't be thrown and I can look at that but does your user have the correct permissions to perform those actions?

**Comment by sagargulati** [comment]
Yeah, it added the document in the db but crashes it as well.

**Comment by mrvautin** [comment]
Ok. Can you please provide the version of MongoDB server you are running?

**Comment by mrvautin** [comment]
Also doesn't appear you are using the latest version of `adminMongo`. There isn't a line 607 in the `/routes/index.js` file in the latest version.

Can you please update and try again?

**Comment by sagargulati** [comment]
I removed the old version and trying to install new version, gives me these errors:

```
> git clone https://github.com/mrvautin/adminMongo
> cd adminMongo
> npm i admin-mongo

```
Got error:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'i', 'admin-mongo' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData admin-mongo
8 silly fetchNamedPackageData admin-mongo
9 silly mapToRegistry name admin-mongo
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/admin-mongo
13 verbose request uri https://registry.npmjs.org/admin-mongo
14 verbose request no auth needed
15 info attempt registry request try #1 at 00:58:57
16 verbose request id f779c7c97f5ed882
17 verbose etag "51PB1FJPEL76PQ0OKSBXDS78X"
18 http request GET https://registry.npmjs.org/admin-mongo
19 http 304 https://registry.npmjs.org/admin-mongo
20 verbose headers { date: 'Sun, 11 Sep 2016 19:28:57 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   etag: '"51PB1FJPEL76PQ0OKSBXDS78X"',
20 verbose headers   age: '147',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-iad2126-IAD',
20 verbose headers   'x-cache': 'HIT',
20 verbose headers   'x-cache-hits': '1',
20 verbose headers   'x-timer': 'S1473622137.683897,VS0,VE0',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 304,
21 silly get   { date: 'Sun, 11 Sep 2016 19:28:57 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     'cache-control': 'max-age=300',
21 silly get     etag: '"51PB1FJPEL76PQ0OKSBXDS78X"',
21 silly get     age: '147',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-iad2126-IAD',
21 silly get     'x-cache': 'HIT',
21 silly get     'x-cache-hits': '1',
21 silly get     'x-timer': 'S1473622137.683897,VS0,VE0',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose etag https://registry.npmjs.org/admin-mongo from cache
23 verbose get saving admin-mongo to /root/.npm/registry.npmjs.org/admin-mongo/.cache.json
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install admin-mongo as a dependency of itself
41 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
41 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
41 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
41 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
41 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
41 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
42 verbose cwd /root/developer/screens/adminMongo
43 error Linux 4.4.0-22-generic
44 error argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "admin-mongo"
45 error node v4.2.6
46 error npm  v3.5.2
47 error code ENOSELF
48 error Refusing to install admin-mongo as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

My NPM & Node version:

```
root@wolf:~/developer/screens/adminMongo# npm -v
3.5.2
root@wolf:~/developer/screens/adminMongo# node -v
v4.2.6
root@wolf:~/developer/screens/adminMongo#

```

**Comment by mrvautin** [comment]
This generally happens when the name of the working folder is the same name as a package that you're trying to install.

Try delete or rename the folder and try again. Same as: https://github.com/mrvautin/adminMongo/issues/103

**Comment by sagargulati** [comment]
Will give it a try! Since this shouldn't even happen if the folder name is same as package!

```
npm install
npm start

```
Running the app on behind 'screen'
Direct works fine!

**Comment by mrvautin** [comment]
That is an NPM issue and occurs on all packages, not just `adminMongo`.

**Comment by sagargulati** [comment]
Yeah i can understand, anyways thanks ^_^
