### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by tawrahim** [mrvautin/adminMongo#120]
Unable to start on my local system because of the error below

```
adminMongo listening on host: http://0.0.0.0:1234
GET / 302 14.174 ms - 66
GET /app/ 302 2.691 ms - 76
/Users/tawheedraheem/node_modules/junk/index.js:24
exports.is = filename => exports.re.test(filename);
                      ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.exports.get_backups (/Users/tawheedraheem/routes/common.js:41:16)
    at /Users/tawheedraheem/routes/index.js:143:16
    at /Users/tawheedraheem/routes/common.js:35:9

npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.5
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! admin-mongo@0.0.20 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-mongo@0.0.20 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the admin-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs admin-mongo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls admin-mongo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
````

**Comment by tawrahim** [comment]
Version of node was old and I also that the issue was already opened [here](https://github.com/mrvautin/adminMongo/issues/106)
