### ISSUE TITLE
Fail with admin authorization

### ISSUE THREAD

**Issue by perqin** [mrvautin/adminMongo#124]
I add an admin user in `admin` database and use the following uri to add a new connection in adminMongo:
```
mongodb://admin:thepass@127.0.0.1:27017/?authSource=admin
```
But then the server throws errors:
```
_http_outgoing.js:346
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at ServerResponse.header (/home/perqin/Apps/adminMongo/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/home/perqin/Apps/adminMongo/node_modules/express/lib/response.js:164:12)
    at done (/home/perqin/Apps/adminMongo/node_modules/express/lib/response.js:956:10)
    at Immediate._onImmediate (/home/perqin/Apps/adminMongo/node_modules/express-handlebars/lib/utils.js:26:13)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/home/perqin/Apps/bin/node" "/home/perqin/Apps/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! admin-mongo@0.0.20 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the admin-mongo@0.0.20 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the admin-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs admin-mongo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls admin-mongo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/perqin/Apps/adminMongo/npm-debug.log
```

**Comment by mrvautin** [comment]
That connection string looks fine. What page/URL are you navigating to when you get the `Can't set headers after they are sent.` error?

**Comment by perqin** [comment]
@mrvautin Just the index `localhost:1234`. Use `mongodb://admin:thepass@127.0.0.1:27017/somedb?authSource=admin` also works. It seems that I must specific a database when using admin account.
