### ISSUE TITLE
Editing documents causes app to crash

### ISSUE THREAD

**Issue by Druzion** [mrvautin/adminMongo#131]
I am quite new to Node.js and NPM so please forgive me if I have done something wrong.

I followed the instructions in the README; I created a directory, navigated into it and ran `npm install admin-mongo`. Everything installed without any errors, however it installed into my user's home directory (`C:\Users\<username>\`).
I continued by running the app and I could open it in the browser and connect to a database.
Everything was working fine, I could view all of the documents, until I tried to edit one, at which point the app crashed with the following error(s):

```
POST /document/<ConnectionName>/<DatabaseName>/<CollectionName>/insert_doc 200 26.025 ms - 73
C:\Users\<username>\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
    at new ObjectID (C:\Users\<username>\node_modules\bson\lib\bson\objectid.js:52:32)
    at ObjectID (C:\Users\<username>\node_modules\bson\lib\bson\objectid.js:31:42)
    at Object.exports.get_id_type (C:\Users\<username>\routes\common.js:157:56)
    at C:\Users\<username>\routes\index.js:429:16
    at C:\Users\<username>\routes\common.js:231:13
    at handleCallback (C:\Users\<username>\node_modules\mongodb\lib\utils.js:95:56)
    at C:\Users\<username>\node_modules\mongodb\lib\cursor.js:852:16
    at handleCallback (C:\Users\<username>\node_modules\mongodb-core\lib\cursor.js:171:5)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\Nodejs\\node.exe" "C:\\Users\\<username>\\AppData\\Roaming\\npm\
\node_modules\\npm\\bin\\npm-cli.js" "start" "app.js"
npm ERR! node v4.2.4
npm ERR! npm  v3.10.2
npm ERR! code ELIFECYCLE
npm ERR! admin-mongo@0.0.20 start: `node app.js "app.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-mongo@0.0.20 start script 'node app.js "app.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the admin-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js "app.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs admin-mongo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls admin-mongo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\<username>\Downloads\adminMongo\npm-debug.log
```

It only ever happens when I attempt to edit a document. Anyone know why? Thanks!

**Comment by mrvautin** [comment]
Apparently this can be causing by running Node v4.x on Windows. Are you able to run on Node version greater than 4.x to see if the issue does away?

I don't have a Windows environment to try replicate.

**Comment by Druzion** [comment]
@mrvautin Yes, it works on Node.js v6.x. Thanks for the help!

**Comment by Druzion** [comment]
@mrvautin I would like to ask though, is it meant to install into your user's home directory? It still does it after updating to Node v6.x. When install it says the following:
```
-=| adminMongo Installation wizard |=-
--------------------------------------------------------
-> Copying installed adminMongo from
C:\Users\<username>\node_modules\admin-mongo\
to
C:\Users\<username>\
--------------------------------------------------------
-> Cleaning after installation...
Completed successfully!
--------------------------------------------------------
-=| adminMongo successfully installed! |=-
```
It says "Cleaning after installation" but the files are still in my user directory. Is this meant to happen?
Thanks!

**Comment by mrvautin** [comment]
Pushed post-install script removal to NPM at is was causing issues.
