### ISSUE TITLE
Not responding.

### ISSUE THREAD

**Issue by staminna** [mrvautin/adminMongo#133]
I installed at per the instructions and first it didn't install in my mkdir directory, but in my home/username/node_modules/admin_mongo.

then, when I open the server on port, I add the mongodb://settings string to the second field and hit add connection button and does nothing. I am certain the string is correct, since I am using it directly from my own nodejs code. I am using authentication on the connection.

$ node app
adminMongo listening on host: http://0.0.0.0:1234
GET /app/connection_list 304 154.535 ms - -
Error: Not Found
    at /Users/jorge/node_modules/admin-mongo/app.js:218:15
    at Layer.handle [as handle_request] (/Users/jorge/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jorge/node_modules/express/lib/router/index.js:312:13)
    at /Users/jorge/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/jorge/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/jorge/node_modules/express/lib/router/index.js:271:10)
    at /Users/jorge/node_modules/express/lib/router/index.js:618:15
    at next (/Users/jorge/node_modules/express/lib/router/index.js:256:14)
    at next (/Users/jorge/node_modules/express/lib/router/route.js:121:14)
    at /Users/jorge/node_modules/admin-mongo/routes/index.js:8:5

Should you require, I'll be happy to provide you with more logs or details. Thanks

**Comment by mrvautin** [comment]
See updated install instructions due to many issues installing directly from NPM: https://github.com/mrvautin/adminMongo/blob/master/README.md 

Try installing again and report back if issue still occurs.

**Comment by staminna** [comment]
Thanks for quick reply. I was able to install it, but not the electron app, says it's missing 
> sh: electron-packager: command not found

A second issue is I can't update my MEAN.JS stack app when I'm connected to adminMongo with  message 

> mongo Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by mrvautin** [comment]
You can manually install `electron-packager` with `npm install electron-packager -g` and you should be able to build/package the electron app.

What URL are you getting 403?

**Comment by mrvautin** [comment]
Closing due to inactivity.
