### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by realflash** [mrvautin/adminMongo#137]
Pulled from github master today.
```
root@percivale:/usr/local/adminmongo# nodejs app

/usr/local/adminmongo/routes/api.js:199
            y: datapoints.reduce((a, b) => a.y + b.y, 0) / datapoints.length
                                         ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/adminmongo/app.js:15:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

I had a quick look but I'm afraid I couldn't work out what type of object datapoints is to work out how reduce should be used, so I couldn't provide a patch.

**Comment by mrvautin** [comment]
What version of Node.Js do you have installed?

**Comment by realflash** [comment]
Stable version for Ubuntu 14.04 LTS, 0.10.25. I realise this is probably old, but the OS will be supported until April 2019. If adminMongo needs a later version of Node.js, could there be a mention of that in the README.md? Thanks.

**Comment by mrvautin** [comment]
`adminMongo` only supports Node.js version 4.0 and above. 

You are totally correct, this should be added to the README.md.

**Comment by mrvautin** [comment]
See f92e5f9c23dc40c5814d898360784d6733a096ba.
