### ISSUE TITLE
After running npm install/npm start failed with error.

### ISSUE THREAD

**Issue by joviledog** [mrvautin/adminMongo#158]
C:\Users\Andy\Source\Repos\adminMongo\routes\api.js:199
            y: datapoints.reduce((a, b) => a.y + b.y, 0) / datapoints.length
                                        ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Andy\Source\Repos\adminMongo\app.js:15:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! admin-mongo@0.0.22 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-mongo@0.0.22 start script 'node app.js'.
npm ERR! This is most likely a problem with the admin-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls admin-mongo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andy\Source\Repos\adminMongo\npm-debug.log

The error I got was captured from C:\Users\Andy\Source\Repos\adminMongo\npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose node symlink C:\Program Files (x86)\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart admin-mongo@0.0.22
7 info start admin-mongo@0.0.22
8 verbose unsafe-perm in lifecycle true
9 info admin-mongo@0.0.22 Failed to exec start script
10 verbose stack Error: admin-mongo@0.0.22 start: `node app.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid admin-mongo@0.0.22
12 verbose cwd C:\Users\Andy\Source\Repos\adminMongo
13 error Windows_NT 6.3.9600
14 error argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v0.12.2
16 error npm  v2.7.4
17 error code ELIFECYCLE
18 error admin-mongo@0.0.22 start: `node app.js`
18 error Exit status 1
19 error Failed at the admin-mongo@0.0.22 start script 'node app.js'.
19 error This is most likely a problem with the admin-mongo package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node app.js
19 error You can get their info via:
19 error     npm owner ls admin-mongo
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by joviledog** [comment]
Never mind, I went to the npm public site and install the latest npm to my Program Files (x86) subfolder and the problem went away.  It could be due to an older version of npm on my Windows PC.  It would be good if the author could publish the minimum npm that one must have to support this nice tool.
