### ISSUE TITLE
TypeError: Cannot read property 'returned' of undefined

### ISSUE THREAD

**Issue by zhikaichen123** [mrvautin/adminMongo#195]
TypeError: Cannot read property 'returned' of undefined
    at getDocCounts (/opt/adminMongo/monitoring.js:103:40)
    at /opt/adminMongo/monitoring.js:61:48
    at /opt/adminMongo/node_modules/mongodb/lib/admin.js:164:7
    at handleCallback (/opt/adminMongo/node_modules/mongodb/lib/utils.js:120:56)
    at /opt/adminMongo/node_modules/mongodb/lib/db.js:998:7
    at /opt/adminMongo/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at process._tickCallback (internal/process/next_tick.js:112:11)

**Comment by shirtgov** [comment]
I'm also having this issue.

**Comment by ibmbootcamp** [comment]
I managed to fix it.

Edit adminMongo/monitoring.js and replace the code for function getDocCounts() with the code below:

function getDocCounts(currCounts, newCounts){
    var newDocCounts = {
        queried: 0,
        inserted: 0,
        deleted: 0,
        updated: 0
    };
    
if(newCounts!==undefined) {
    // querie
    if(currCounts.queried === 0){
        currCounts.queried = newCounts.returned;
    }else{
        newDocCounts.queried = newCounts.returned - currCounts.queried;
        currCounts.queried = newCounts.returned;
    }


    // inserts
    if(currCounts.inserted === 0){
        currCounts.inserted = newCounts.inserted;
    }else{
        newDocCounts.inserted = newCounts.inserted - currCounts.inserted;
        currCounts.inserted = newCounts.inserted;
    }

    // deleted
    if(currCounts.deleted === 0){
        currCounts.deleted = newCounts.deleted;
    }else{
        newDocCounts.deleted = newCounts.deleted - currCounts.deleted;
        currCounts.deleted = newCounts.deleted;
    }

    // updated
    if(currCounts.updated === 0){
        currCounts.updated = newCounts.updated;
    }else{
        newDocCounts.updated = newCounts.updated - currCounts.updated;
        currCounts.updated = newCounts.updated;
    }
}
    return newDocCounts;
}

**Comment by gbhrdt** [comment]
For anyone looking for a quick workaround, you can pull `gbhrdt/adminmongo` which includes the fix from @ibmbootcamp
