### ISSUE TITLE
can not open the website with execute file ，version is 1.0.0

### ISSUE THREAD

**Issue by sheiy** [mrvautin/adminMongo#213]
Error: Not Found
    at C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\app.js:181:15
    at Layer.handle [as handle_request] (C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\node_modules\express\lib\router\index.js:271:10)
    at C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\node_modules\express\lib\router\index.js:618:15
    at next (C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\node_modules\express\lib\router\index.js:256:14)
    at next (C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\node_modules\express\lib\router\route.js:121:14)
    at C:\Users\Sofior\Downloads\adminMongo_Win64\resources\app\routes\index.js:8:5

**Comment by gabefair** [comment]
What version of node do you have installed?

**Comment by sofior** [comment]
8.11.3

**Comment by sofior** [comment]
@gabefair 
adminmongo v1.2.6 windows x64 
node v10.8.0
npm 6.2.0
open the exe file I got a white page,I can open 127.0.0.1:1234 in chrome
