### ISSUE TITLE
Error, after connect, if auth enabled

### ISSUE THREAD

**Issue by Rastopyr** [mrvautin/adminMongo#24]
Hello. I have issue with connecting to mongod with enabled authentication

I start mongod like this `mongod --auth --syslog --fork`

Then i try connect to my database with adminMongo.
`mongodb://admin:pass@hostname:27017/dbname`
User `admin` and database `dbname` already exist in my mongo.
And i get error:
```
TypeError: Cannot read property 'size' of undefined
    at /home/adminMongo/routes/index.js:1130:58
    at handleCallback (/home/adminMongo/node_modules/mongodb/lib/utils.js:96:12)
    at /home/adminMongo/node_modules/mongodb/lib/db.js:299:20
    at /home/adminMongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:778:46
    at Callbacks.emit (/home/adminMongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/home/adminMongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/home/adminMongo/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)

```

If i not pass `--auth` param to mongod, with authentication it's all ok.

**Comment by mrvautin** [comment]
Can you try omitting the dbname from your connection string?

**Comment by Rastopyr** [comment]
@mrvautin it work. thank you!

**Comment by mrvautin** [comment]
Need to build in some better error handling around the gathering of stats. If cannot get stars for collection, need to return a null or "n/a" value.
