### ISSUE TITLE
can't start app.js straight after cloning repo

### ISSUE THREAD

**Issue by arakno** [mrvautin/adminMongo#50]
Hi , when starting fetching dependencies:
> npm start 

It stops with an error on module.js :327 , and I can't find any file with that name.

This is the npm-debug.log:

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\pbasto\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.8.1
3 info using node@v4.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle admin-mongo@0.0.3~prestart: admin-mongo@0.0.3
6 silly lifecycle admin-mongo@0.0.3~prestart: no script for prestart, continuing
7 info lifecycle admin-mongo@0.0.3~start: admin-mongo@0.0.3
8 verbose lifecycle admin-mongo@0.0.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle admin-mongo@0.0.3~start: PATH: C:\Users\pbasto\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;c:\Users\pbasto\Projects\adminMongo\node_modules\.bin;C:\Program Files\nodejs;C:\Users\pbasto\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Common Files\Adobe\AGL;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Skype\Phone\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\pbasto\AppData\Local\Programs\Git\cmd;C:\Users\pbasto\AppData\Roaming\npm
10 verbose lifecycle admin-mongo@0.0.3~start: CWD: c:\Users\pbasto\Projects\adminMongo
11 silly lifecycle admin-mongo@0.0.3~start: Args: [ '/d /s /c', 'node app.js' ]
12 silly lifecycle admin-mongo@0.0.3~start: Returned: code: 1  signal: null
13 info lifecycle admin-mongo@0.0.3~start: Failed to exec start script
14 verbose stack Error: admin-mongo@0.0.3 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\pbasto\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\pbasto\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid admin-mongo@0.0.3
16 verbose cwd c:\Users\pbasto\Projects\adminMongo
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pbasto\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v4.3.1
20 error npm  v3.8.1
21 error code ELIFECYCLE
22 error admin-mongo@0.0.3 start: `node app.js`
22 error Exit status 1
23 error Failed at the admin-mongo@0.0.3 start script 'node app.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the admin-mongo package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs admin-mongo
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls admin-mongo
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Thanks

**Comment by arakno** [comment]
Actually just stumbled with a stackoverflow answer which solved my issue:

[http://stackoverflow.com/questions/14226410/node-js-cannot-find-module-mongodb](url)

`npm install mongodb -g
cd /path/to/my/app/folder
npm link mongodb`

this fixed it for me and I was able to start the app
