### ISSUE TITLE
"Error - Not Found" with 1.0.0

### ISSUE THREAD

**Issue by klonos** [mrvautin/adminMongo#95]
```
Error: Not Found
    at /home/user/public_html/adminMongo/app.js:181:15
    at Layer.handle [as handle_request] (/home/user/public_html/adminMongo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/user/public_html/adminMongo/node_modules/express/lib/router/index.js:312:13)
    at /home/user/public_html/adminMongo/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/user/public_html/adminMongo/node_modules/express/lib/router/index.js:330:12)
    at next (/home/user/public_html/adminMongo/node_modules/express/lib/router/index.js:271:10)
    at /home/user/public_html/adminMongo/node_modules/express/lib/router/index.js:618:15
    at next (/home/user/public_html/adminMongo/node_modules/express/lib/router/index.js:256:14)
    at next (/home/user/public_html/adminMongo/node_modules/express/lib/router/route.js:121:14)
    at /home/user/public_html/adminMongo/routes/index.js:8:5
```

**Comment by lefdilia** [comment]
yes the problem is in "routes/index.js"
https://github.com/mrvautin/adminMongo/compare/master...lefdilia:patch-5

**Comment by klonos** [comment]
Yep, fixed. Thanx 😉

**Comment by mrvautin** [comment]
Seems the link above is dead. Was fixed in PR: https://github.com/mrvautin/adminMongo/pull/96.
