### ISSUE TITLE
Inserting document with "_id" field will stop adminMongo

### ISSUE THREAD

**Issue by yaliv** [mrvautin/adminMongo#97]
Hello,

Thanks for sharing this project. I found it is easy to use and has some features I need, such as manage multiple connections and export data to a JSON file.

The problem I have is when **inserting data**. And actually, I have **two sub-problems** which I think I should post them in separate issues.

When I inserted a document with `"_id"` field, nothing happened in the app but it turned out adminMongo logged some errors and then **stopped!**
```
Amna@Amna-PC MINGW32 /d/MASTER-DEV/DATABASE/MongoDB/adminMongo
$ npm start

> admin-mongo@0.0.17 start D:\MASTER-DEV\DATABASE\MongoDB\adminMongo
> node app.js

adminMongo listening on host: http://0.0.0.0:1234
POST /document/Lokal/goinggo/demo_users/doc_delete 200 291.792 ms - 39
POST /api/Lokal/goinggo/demo_users/1 200 1308.528 ms - 568
POST /document/Lokal/goinggo/demo_users/doc_delete 200 27.447 ms - 39
POST /api/Lokal/goinggo/demo_users/1 200 25.941 ms - 118
GET /app/Lokal/goinggo/demo_users/new 304 714.737 ms - -
GET /bootstrap/css/bootstrap.min.css 304 31.515 ms - -
GET /css/flatly.bootstrap.min.css 304 21.694 ms - -
GET /css/highlightjs.github.min.css 304 8.829 ms - -
GET /css/style.css 304 6.125 ms - -
GET /font-awesome/css/font-awesome.min.css 304 20.211 ms - -
GET /jquery/jquery.min.js 304 11.279 ms - -
GET /bootstrap/js/bootstrap.min.js 304 18.729 ms - -
GET /js/ace/ace.js 304 6.197 ms - -
GET /js/toEJSON.js 304 15.579 ms - -
GET /js/editor.js 304 5.462 ms - -
GET /js/adminMongo.js 304 9.218 ms - -
GET /js/highlight.min.js 304 7.475 ms - -
GET /static/logo.png 304 8.876 ms - -
GET /fonts/glyphicons-halflings-regular.woff2 304 5.348 ms - -
GET /js/ace/theme-github.js 304 7.081 ms - -
GET /js/ace/mode-json.js 304 10.923 ms - -
D:\MASTER-DEV\DATABASE\MongoDB\adminMongo\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property '0' of undefined
    at D:\MASTER-DEV\DATABASE\MongoDB\adminMongo\routes\document.js:43:104
    at handleCallback (D:\MASTER-DEV\DATABASE\MongoDB\adminMongo\node_modules\mongodb\lib\utils.js:96:12)
    at Object.cb (D:\MASTER-DEV\DATABASE\MongoDB\adminMongo\node_modules\mongodb\lib\collection.js:1041:5)
    at D:\MASTER-DEV\DATABASE\MongoDB\adminMongo\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:446:18
    at authenticateStragglers (D:\MASTER-DEV\DATABASE\MongoDB\adminMongo\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:402:16)
    at null.messageHandler (D:\MASTER-DEV\DATABASE\MongoDB\adminMongo\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:424:5)
    at Socket.<anonymous> (D:\MASTER-DEV\DATABASE\MongoDB\adminMongo\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:294:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! admin-mongo@0.0.17 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the admin-mongo@0.0.17 start script 'node app.js'.
npm ERR! This is most likely a problem with the admin-mongo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs admin-mongo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls admin-mongo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\MASTER-DEV\DATABASE\MongoDB\adminMongo\npm-debug.log

Amna@Amna-PC MINGW32 /d/MASTER-DEV/DATABASE/MongoDB/adminMongo
$
```
But when I started it again and checked the data in my collection, the document is inserted as expected.

It's no problem if the inserted document doesn't contain the `"_id"` field. But if I use the `"_id"` field again, the same error occurs.

**Comment by yaliv** [comment]
Great! Thanks for the quick fix.
:+1:
